### PR TITLE
feat: support o200k_base (gpt-4o)

### PR DESCRIPTION
**Pull request by WqyJh**
- support o200k_base encoding
- fix benchmark for udhr url 404

### CODE REVIEW

**Comment by sash20m** [comment]
Do you happen to know what is the token count for gpt-4o ? They said it's less then previous models, it it's probably less than 3 (as for gpt-4)
Refference: https://github.com/pkoukk/tiktoken-go#counting-tokens-for-chat-api-calls

**Comment by WqyJh** [comment]
Yes it's for gpt-4o

**Comment by sash20m** [comment]
> Yes it's for gpt-4o

Yes, but I mean what is the token per messge, as in the number. Is it 3 like for gpt-4 or 4 like for gpt-3.5 (unlikely). If you know of course, it's possible to calculate with code the link provided above but haven't tried.

**Comment by WqyJh** [comment]
Well, currently not sure. I didn't find any clusion of it currently.

But I believe it's the same with gpt-4 currently. I've just say `hi` to gpt-4o and gpt-3.5-turbo, the input/output tokens is the same. And I count the tokens when `stream=true`, it's also the same.

image

If openai didn't mention that it's changed, then it's probably not changed. But it might be changed after the voice & video capabilities of gpt-4o was released.

- https://github.com/openai/openai-cookbook/blob/main/examples/gpt4o/introduction_to_gpt4o.ipynb
- https://github.com/openai/openai-cookbook/blob/main/examples/How_to_count_tokens_with_tiktoken.ipynb

**Pull request merged**
